---
# Local Vagrant options.
vagrant_hostname: local.drupalvm.com
vagrant_machine_name: local-drupalvm
vagrant_ip: 192.168.88.10

# Configure the synced folder.
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    type: nfs

# Undo some of the extra-hardened security settings in config.yml.
drupal_account_pass: admin
drupal_db_password: drupal
mysql_root_password: root

php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  - drush
  - mailhog
  - varnish
  - solr

dashboard_install_dir: /var/www/dashboard
extra_security_enabled: false

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
firewall_log_dropped_packets: false

# Set Apache to listen on port 80, and Varnish on 81.
apache_listen_port: "80"
varnish_listen_port: "81"
varnish_default_backend_port: "80"
